### ISSUE TITLE
Can you add README file for this project?

### ISSUE THREAD

**Issue by dinesh-matta-mpf** [rherwig/template-react-16-ssr#1]
Hi @rherwig,

I really liked your implementation of react-16's  server-side rendering. I like to understand this example better, so would need some assistance in understanding the code. As I am also planning to create react app with will have ssr feature, which will have backend express app which will call some third party api and render the response to react components.

Thanks!!

**Comment by rherwig** [comment]
Sure, I'm working on that. 

Any particular information you wish for?

**Comment by zolero** [comment]
Are you going to make a build environment too?

**Comment by rherwig** [comment]
I will. On it atm.

**Comment by rherwig** [comment]
I added build scripts and a basic readme. For further documentation please refer to the documentation inside the code or create an issue with your specific question. :-)
