### ISSUE TITLE
code splitting ?

### ISSUE THREAD

**Issue by arkhamRejek** [rherwig/template-react-16-ssr#14]
Hey thank you for this awesome template but is there any reason you aren't implementing the code splitting with react-universal-component or am i missing something. The code snipet below throws an error saying 
[FLUSH CHUNKS]: Unable to find default in Webpack chunks. Please check usage of Babel plugin.

``` javascript 
import Login from "../shared/pages/auth/login"
import Container from "../shared/components/container"

const UniversalComponent = universal((props) => import(`../shared/pages/auth/login.js`))

const routes = () => {
    return (
        <Switch>
            <Container>
                <Route path="/" component={UniversalComponent} />
            </Container>
        </Switch>
    )
}

**Comment by rherwig** [comment]
Hey,
I just set up a simple test case and was not able to reproduce the error.
Which feature branch are you using?

**Comment by arkhamRejek** [comment]
That's the same effect I got, I might ask I'll bother Facey on Reactlandia chat to see what he thinks. I'll update if i get anything back.

**Comment by rherwig** [comment]
@arkhamRejek Thanks so much! I'll also look into the issue this weekend.

**Comment by arkhamRejek** [comment]
@rherwig haven't had much luck digging into it so far, Facey has been busy with other projects so he hasn't been able to reply much. A friend of mine said that https://github.com/jamiebuilds/react-loadable is working on webpack 4 for him with no issues.

**Comment by rherwig** [comment]
@arkhamRejek I also stumbled over this, while looking for a solution to fix universal component. I'll try it out.

**Comment by rherwig** [comment]
As of now, there is still an open PR on react-loadable to implement the webpack 4 API. I guess I will wait and try to work something out with universal component

**Comment by arkhamRejek** [comment]
pull open
https://github.com/rherwig/template-react-16-ssr/pull/15

**Comment by rherwig** [comment]
Thanks @arkhamRejek! I'm gonna test and review it later today
