### ISSUE TITLE
where does universal get its path from

### ISSUE THREAD

**Issue by dagda1** [rherwig/template-react-16-ssr#16]
In your UniversalComponent, your component looks like this:

```
import universal from 'react-universal-component';

export default universal(({ name }) => import(`./${name}`));
```

How is the path `./${name}/` resolving?  Is the `cwd()` not the root of the site?

I am confused as to how this is working.

**Comment by rherwig** [comment]
Despite the fact, that this is closed, for future reference:

Universal Component's root is the `shared/components` directory. This is signified by the `./` which resolves to the path of the file.
