### ISSUE TITLE
Webpack 4 and our chunking system

### ISSUE THREAD

**Issue by zackljackson** [rherwig/template-react-16-ssr#17]
Might help you bro!

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/60

**Comment by rherwig** [comment]
@zackljackson Thanks a lot! I'll have a look. Would be nice to have working CSS chunks once again :-)

**Comment by zackljackson** [comment]
It’s already done ✅ just updating readmes and cleaning a bunch of stuff up. Beta testing and feedback would be valuable ❤️🙏 PRs are also welcome if you spot something off the bat 

Main thing is I want awesome chunking back 😂 its a massive re-rewrite so beta testing is important. 

There’s almost half a million installs 😆 safety first

**Comment by rherwig** [comment]
I'm taking a look at it right this evening and will of course submit feedback

**Comment by zackkirsh** [comment]
Awesome, ill be pushing commits throughout the day, just drop a line if you have a question

**Comment by rherwig** [comment]
I tried to implement the version from your current webpack-4 branch and ran into a build-time issue.

I basically set it up like your documentation says, which mainly involves the webpack config:
https://github.com/rherwig/template-react-16-ssr/blob/development/webpack/client.js

Everything but HMR works with mini-extract-css-chunks. If you want to take a look at the issue, please refer to the development branch of this repository :-)

**Comment by zackljackson** [comment]
Found it. Gimme a few

**Comment by zackljackson** [comment]
Okay done, should work for you now. Thanks for beta testing! Ill need to write tests for this

**Comment by rherwig** [comment]
Yay! It works now! :-) Thanks for the effort so far, I'm gonna go on and test it a little more now

**Comment by zackljackson** [comment]
Fantastic!! More than welcome. 

If you have some spare time. Id greatly appreciate it if you can add / extend a test to prevent this happening.

Let me know if you spot anything else

**Comment by zackljackson** [comment]
Aaaaaaand it’s releaeed! V3.x.x is on npm 🎉🎉
