### ISSUE TITLE
Should we use eslint?

### ISSUE THREAD

**Issue by rherwig** [rherwig/template-react-16-ssr#18]
Hey everyone,

I've been thinking about implementing eslint for this project, but am not exactly sure, if this is a good idea... code-style is to a certain degree a matter of commitment in a team after all. So I don't know, if it would be wise to provide an opinion on code style via eslint.

What do you think? Eslint - yes/no? Via webpack-loader or just the config and an npm lint task for those who'd like to use it?

**Comment by zackljackson** [comment]
Yes! You want it! 

Linking can standardize how code is written. For example, I can have a lint rule enforcing specific export practices, which go hand in hand with code splitting and optimization 

Linting let’s you define an environment so people don’t end up using browser code in node. Things like that. 

Plus it’s free indentations , cleaning and standardized look. 

Not much hassle and doesn’t take long to lint a project. With distributed teams, you need something to standardize the codebase.

**Comment by rherwig** [comment]
Right, I also see that linting is requried, but I still wonder to what extent. If implemented via webpack eslint loader, linting would be enforced for all users unless they disable it explicitly. I don't think, this is a bad thing, but the question is: what config? I personally tend to use AirBnBs eslint config a lot or at least some slight variant of that.

**Comment by rherwig** [comment]
ESLint has been implemented in the current release https://github.com/rherwig/template-react-16-ssr/tree/3.0.0
