### ISSUE TITLE
How does this work with express routing?

### ISSUE THREAD

**Issue by KingScooty** [rherwig/template-react-16-ssr#2]
This is a really nice example. I'm a little confused where express routing would live though. Webpack seems to be doing quite a lot of stuff in the middle—between `/src/index.js` and `/src/server/index.js`. I can't seem to figure out how to access the Express `app` variable that's defined in `src/index.js` in any other files.

What would be the best practices to adding express level routing to this project?

**Comment by rherwig** [comment]
This depends on what you want to achieve. If you are talking API, you can implement your routes like normal (using app.get / app.post / ...). You could add a `configureRoutes()` method in `src/index.js` and call it before the environment is configured.

If you want to achieve 'regular' routing, meaning displaying different pages, express would not the place to add them. React SSR apps use libs like `react-router` to achieve server- and client-side routing.

So what exactly do you need express level routes for?

**Comment by crabbits** [comment]
@rherwig maybe I could create another feature branch showing how to do API calls from express? I have an app calling the mailchimp API I can work off to provide an example.

Also @KingScooty theres a new branch that shows how to do routing using react-router that might help you, check the Readme for details.

**Comment by rherwig** [comment]
@crabbits: I just provided an example for express routing in the feature/express-routing branch.
Provide some feedback if you like.

https://github.com/rherwig/template-react-16-ssr/tree/feature/express-routing

**Comment by rherwig** [comment]
For those that encountered a module resolution bug when using the prod build, see #9. The bug has been resolved.
