### ISSUE TITLE
EJS rendering for SEO

### ISSUE THREAD

**Issue by manish4781** [rherwig/template-react-16-ssr#24]
Hi,
i am trying to render my component on server, a component which fetches the data from another 3rd party API on **componentDidMount**, my component is rendering fine but when is pass the string returned from **ReactDOM.renderToString** to my **.ejs** file which is missing the data returned from 3rd party API 

```
import React from 'react';
import ReactDOM from 'react-dom/server';
import { flushChunkNames } from 'react-universal-component/server';
import flushChunks from 'webpack-flush-chunks';

import App from '../shared/App';
import HorizontalModule from '../shared/Horizontal-module';
export default ({ clientStats }) => async (req, res) => {
    const app = (
        <App/>
    );
 
    const appString = ReactDOM.renderToString(app);
    const chunkNames = flushChunkNames();
    const { js, styles, cssHash } = flushChunks(clientStats, { chunkNames });
    res.render('index', {
        appString,
        js,
        styles,
        cssHash
    });

    console.log(appString);
};

```
my <App> component is rendering fine, but when is see the view-source of a page component is empty.
**appString** is basically empty

this is where my component rendered http://ec2-13-232-170-86.ap-south-1.compute.amazonaws.com:3000/

and this is my code base https://github.com/sharmam1/testproj

**Comment by rherwig** [comment]
The issue with that is, that the app is rendered on the server-side correctly, but no data can be fetched during toString rendering. This is a limitation of SSR.

To overcome this, you want to fetch the data on the server side, before rendering your application with renderToString. The fetched data can then be rendered to the template and reused in the client side application. This concept is called 'state hydration'.

I would encourage you to have a look the the `feature/redux` branch of this project, where the general concept is employed.

https://github.com/rherwig/template-react-16-ssr/blob/feature/redux/src/server/index.js

The `preloadedState` you see in this file would have to be your API data.

If there are any further questions, feel free to ask ;-)

**Comment by manish4781** [comment]
HI @rherwig,
thanks for the reply, i was wondering if there is a way to achieve this without using redux?
any help would be appreciated.

**Comment by manish4781** [comment]
Hi @rherwig ,
can you give some example of how do i pass data from server to client as props, if i fetch data on server itself and try to reuse it on client.

**Comment by rherwig** [comment]
Please refer to #25, since this is a duplicate with a short example. Comment on the issue, if there are question or you need a full example, as I might look into providing one.
