### ISSUE TITLE
svg jpg file load

### ISSUE THREAD

**Issue by manish4781** [rherwig/template-react-16-ssr#26]
Hi @rherwig i have few question, i am new to webpack
1) I am trying to import svg, jpg file but i get the error
**Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.**
If you have any example to add loaded for these files

2) what is the use of this https://github.com/rherwig/template-react-16-ssr/blob/feature/react-router/webpack/client.js#L39 why are we including bootstrap,
as i see bootstrap.js is added in my DOM, is there a way i can remove it(should i remove it)

**Comment by rherwig** [comment]
Hey there!

1. There is a [file-loader](https://github.com/webpack-contrib/file-loader) for webpack that is well documented. You want to add this to the webpack config. I will, however, expand this template to load an image (i.e. favicon) this evening, so if you are not able to implement file-loader yourself, stay tuned.

2. This is not actually the bootstrap framework, but rather a bootstrap script that webpack needs to get things started. I would advise you though, to use the current master branch of the template, since this bootstrap chunk was a thing in webpack 3 (webpack 4 is the current version).

Any other questions? Let me know!

**Comment by sharmam1** [comment]
You are always a great help, thanks @rherwig , i'll use latest master,

although i am getting an error when i am running **npm run build** 
**> react-ssr-template@2.4.0 build:node /Users/Documents/master/template-react-16-ssr
> cross-env NODE_ENV=production webpack -p --config webpack/node.production.js

/Users/Documents/master/template-react-16-ssr/scripts/extended-node-externals.js:8
    ...nodeExternals,
    ^^^
SyntaxError: Unexpected token ...**

 Also i have few doubts.
1) what is the use of **extended-node-externals.js** and **node-externals.js** 
2) for doing prod build, is it the correct step: 
Set env variable to **production**
npm i --production
npm run build
npm start ?

**Comment by rherwig** [comment]
1. `node-externals` is used to tell webpack that the node_modules are installed separately. This is used for building pure node js apps, like express servers. This is done, so the node_modules are not part of the final bundle. The `extended-node-externals` are a custom file that I created. Those are used to tell webpack to not include assets like the server-bundle. This bundle is dynamically required by the express server and used by express at the same time. Not excluding this would result in circular dependencies. The extended node externals have been introduced to enable the node server to be processed by webpack in production.

2. To trigger a production build and execute it, follow these steps:
```
$ npm run build
$ node public/index
```

The environment `production` is set for you by `npm run build`. The result of the build is deployed inside the `public/` directory. So whenever you want to move the production app to another server, copy the contents of the `public/` directory over to the server, run `npm i` and `node index`.

Regarding the `SyntaxError: Unexpected token ...`:
The `...` is called 'spread operator' and is part of the most recent ECMAScript specs.

Please verify to things:
1. You have a current version of NodeJS installed (best would be >= 8)
2. The project root contains a `.babelrc` file. This is part of the master branch, but might get lost if you did not `git clone` the branch, but downloaded it as a zip file (zip does not like files starting with a dot).

Let me know, if this helped you :-)

**Comment by sharmam1** [comment]
This worked, thanks @rherwig, when i upgraded to node v8+.

i had one doubt about code splitting i have some component in shared directory which has Localstorage logic, as i am converting everything to SSR and component rendering on server, but it shows the error **Window not defined** as window not initialized at that point of time, is there a way to handle this situation. or to ask a general question how can we render a component which has a client side code written?

**Comment by rherwig** [comment]
The problem is that `window` is a browser API and thus not available on the server. The solution is, to write code that does not rely on the `window` object and use isomorphic libraries that do so as well.

If `window` just can not be avoided, the following would be possible:
```
if (typeof window !== 'undefined') {
  // your code using window
}
```

**Comment by sharmam1** [comment]
Hey @rherwig, is there a better way to handle the rendering situation if i use cookie in place of Localstorage in current template, any example if i can use cookie value at server side and then use it.

**Comment by manish4781** [comment]
@rherwig just checking if the template is supporting file system(jpg, svg) as an import function?
also will it be possible to include to load fonts file as well.

**Comment by rherwig** [comment]
File system "imports" are only possible on the NodeJS side via `fs.readFile()`. Did you mean that? Like importing `C:\profile.jpg`. ?

**Comment by manish4781** [comment]
i meant to load a favicon images.

**Comment by rherwig** [comment]
You can, although with ejs it is not that nice.

You can pass parameters to the EJS template, like it is aleady done:
https://github.com/rherwig/template-react-16-ssr/blob/18d6dd416e514743c3f6ee6285c5a03adf481682/src/server/index.js#L27

There you could do:
```
res.render('index', {
  favicon: require('path/to/icon.png')
});
```

I am rethinking the whole EJS thing a.t.m anyways, since using a JS file to render the document seems more practical
