### ISSUE TITLE
How can we create router config 

### ISSUE THREAD

**Issue by sitambas** [rherwig/template-react-16-ssr#3]
I want multiple url and component wise create chunk it is possible to do that

**Comment by rherwig** [comment]
The goto would be to use react-router. It enables you to do client-side/server-side routing as well as chunking routes.

https://github.com/ReactTraining/react-router

I'm currently working on an example that will be available on a separate branch of this repository once it's done

**Comment by crabbits** [comment]
@rherwig I have an example working with react-router that I'm happy to open a PR for, I can't seem to push to the repo though.

**Comment by rherwig** [comment]
PRs are greatly appreciated, as I only have little time to work on the template myself. 
You first need to fork the repository and create a custom feature branch. Then you can submit a PR. :-)

**Comment by crabbits** [comment]
Perfect, I'm heading back to Melbourne tonight so I'll get a PR out over the next day.

**Comment by crabbits** [comment]
https://github.com/rherwig/template-react-16-ssr/pull/4

I'm about to get on a flight so I'll do the redux one tomorrow

**Comment by rherwig** [comment]
After a bit of chaos, I got the PR accepted. Extended the README on master to reference your contribution and create feature/react-router. Thanks again :-)

**Comment by crabbits** [comment]
@rherwig No problems thank you for such a  great template. If there's anything I could have done to make your job easier let me know, I haven't contributed to open source for a while so I'm a bit rusty.

**Comment by rherwig** [comment]
I initially created this template to provide a boilerplate to my colleagues. :-)
But since people seem to like it, let's expand on that.

If there are any ideas or possible refactorings, please don't hesitate to open an issue or PR.
And thanks a lot for your contributions so far!
