### ISSUE TITLE
Am I right in understanding that the feature branches are now behind the master branch?

### ISSUE THREAD

**Issue by dwjohnston** [rherwig/template-react-16-ssr#32]
I'm basically trying to get this to work with Redux and React-Router. 

Am I right in that there have been changes (mostly -  switching to Helmet) - that have made Master 3.0.0 incompatible  (or at least  requiring updating/merging resolution) with the feature branches?

In anycase - here's my attempt to catch feature/redux up with master: 

https://github.com/dwjohnston/template-react-ssr/tree/feature/redux-catchup

**Comment by rherwig** [comment]
You're right - the feature branches are behind. This is actually my current todo. Expect the branches to be up to date again within the next week.

As for now, use them as a conceptual guideline on how to implement the different components.

Your branch looks pretty good so far and I would be happy to review an upcoming pull request in more detail, if you choose to submit one. :-)

**Comment by dwjohnston** [comment]
I'm no git pro - what is the correct way to resolve this? Cherry pick? Rebase?

**Comment by dwjohnston** [comment]
The thing I'm concerned about - (and what I've been running into) is a situation where the heads get mixed up or whatever and the branches no longer merge into each other without conflicts.

**Comment by rherwig** [comment]
Usually, rebase would be the go to way. Since there have been some breaking changes in 3.0 (like getting rid of ejs) this might not be the easiest way. 

My current approach is, to "re-implement" the features of the different feature branches, since I am reviewing them anyway in order to see, if more optimal implementations are possible given the improvements made in libs like redux, etc.

**Comment by dwjohnston** [comment]
>My current approach is, to "re-implement" the features of the different feature branches, since I am reviewing them anyway in order to see, if more optimal implementations are possible given the improvements made in libs like redux, etc.

Mmm - I was thinking of doing that to. Just wondering if there's a nicer way to do it. 

Currently if i do: 

```
git checkout feature/react-router
git merge master
```

This merges with no issues, but it removes all of the react-router functionality. What I would like to do is have all of the commits between where the branches diverged, and then apply all the feature/react-router changes on top of that - and then manually fix the errors.
