### ISSUE TITLE
Build problem on feature/express-routing branch

### ISSUE THREAD

**Issue by jorgeitenjr** [rherwig/template-react-16-ssr#9]
I'm trying to run the builded version of the branch with: node public/index.js
and getting:
`Error: Cannot find module './server/api'`
Not sure why webpack isnt the api.

**Comment by rherwig** [comment]
Snap! You're right. The node server code is not bundled by webpack. Gotta fix that. Thanks for reporting.

**Comment by rherwig** [comment]
Fixed this by implementing a webpack build for `src/index` as well (#10).

**Comment by jorgeitenjr** [comment]
Nice. You did a good job in this repo, btw. Thanks.

**Comment by rherwig** [comment]
Thanks! :-) If there are any requests, optimizations or the like, please open an issue, as it helps to improve the quality and usefulness even further
